dist: trusty
language: java
jdk: oraclejdk8
install: mvn dependency:go-offline
script:
  - mvn test -B -V
  - bash <(curl -s https://codecov.io/bash) -c -F unit
  - mvn clean verify -Dskip.surefire.tests=true -B -V
  - bash <(curl -s https://codecov.io/bash) -c -F integration